flask_app/__init__.py
from flask import Flask
from os import getenv
from .views import home, analysis


def create_app():
    app = Flask(__name__, static_folder='static', static_url_path='')

    app.register_blueprint(home.bp)
    app.register_blueprint(analysis.bp)
    app.secret_key = getenv("FLASK_SECRET_KEY")

    return app

flask_app/views/analysis.py
from concurrent.futures import ThreadPoolExecutor
from analysis.tweets_analysis import analyse_symbol
from api.mediastack_api import get_financial_news
from flask import (
    Blueprint, redirect, render_template, flash, request, session
)
import yfinance as yf


bp = Blueprint('analysis', __name__)

@bp.route('/analysis/<symbol>')
def analysis(symbol):
    # Get up to 5 items to display for each section and pass them
    # as a list of dictionary with relevant data
    n_display = 5
    bullish_tweets_display = []
    bearish_tweets_display = []
    news_article_display = []

    # Whether current symbol is favourited by user in session information
    is_favourite = symbol in session.get('favourites', [])

    # Use multithreading for the API calls required
    with ThreadPoolExecutor(max_workers=5) as executor:
        get_stock_info = lambda symbol: yf.Ticker(symbol).info
        stock_info_future = executor.submit(get_stock_info, symbol)
        analysis_future = executor.submit(analyse_symbol, symbol)
        financial_news_future = executor.submit(get_financial_news, symbol, n_display)

        stock_info = stock_info_future.result()
        if len(stock_info) == 1:
            # Stock does not exist from lookup on Yahoo Finance
            flash('No matching company listing found')
            return redirect('/')

        analysis = analysis_future.result()
        company_name = stock_info['shortName']
        price_movement_prediction = "RISE" if analysis['is_bullish'] else "FALL"
        confidence_level = "{:.2f}".format(analysis['confidence_level'])
        bullish_tweets = analysis['bullish_tweets']
        bearish_tweets = analysis['bearish_tweets']

        # Add dictionaries to each list of display tweets, each containing
        # a 'text' and 'link' key
        for i in range(min(n_display, len(bullish_tweets))):
            tweet = bullish_tweets[i]
            bullish_tweets_display.append({'text': tweet.get_truncated_text(),
                                        'link': tweet.get_link()})

        for i in range(min(n_display, len(bearish_tweets))):
            tweet = bearish_tweets[i]
            bearish_tweets_display.append({'text': tweet.get_truncated_text(),
                                        'link': tweet.get_link()})


        # Get 5 most recent financial news about the symbol to display
        financial_news = financial_news_future.result()
        for i in range(min(n_display, len(financial_news))):
            article = financial_news[i]
            news_article_display.append({'title': article.get_truncated_title(),
                                        'link': article.url})
        

        return render_template('analysis.html', is_favourite=is_favourite, symbol=symbol, company_name=company_name, 
        prediction=price_movement_prediction, confidence_level=confidence_level, bullish_tweets=bullish_tweets_display, 
        bearish_tweets=bearish_tweets_display, news=news_article_display)


@bp.route('/add-favourites', methods=['GET', "POST"])
def add_favourite():
    if request.method == 'POST':
        symbol = request.form.to_dict()['symbol']
        # Favourites list exist in session, add symbol to list if
        # not already favourited, else remove it from list
        if session.get('favourites'):
            favourites = session['favourites']
            if symbol not in favourites:
                favourites.append(symbol)
            else:
                favourites.remove(symbol)
            
            session['favourites'] = favourites

        # Favourites list not in session, create new list with given symbol
        else:
            session['favourites'] = [symbol]

        return analysis(symbol)

flask_app/views/home.py
from flask import (
    Blueprint, render_template, request
)
from .analysis import analysis
from analysis.models import analyse_sentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from analysis.cache import get_recommended_stocks


analyzer = SentimentIntensityAnalyzer()
bp = Blueprint('index', __name__)

@bp.route('/', methods=('GET', 'POST'))
def home():
    if request.method == 'POST':
        ticker = request.form['ticker'].upper()
        return analysis(ticker)

    recommended_stocks = get_recommended_stocks()
    return render_template('index.html', recommended_stocks=recommended_stocks)


@bp.route('/contact', methods=["GET"])
def contact():
    return(render_template('contact.html'))


@bp.route('/about', methods=["GET"])
def about():
    return(render_template('about.html'))


@bp.route('/ai', methods=["GET", "POST"])
def ai():
    if request.method == 'POST':
        input = request.form['input']
        type = request.form['type']
        if type == 'financial-sentiment':
            sentiment, score = analyse_sentiment(input)
            return f"{{Sentiment: {sentiment.upper()}, Confidence score: {'{:.2f}'.format(abs(score))}}}"

        elif type == 'general-sentiment':
            score = analyzer.polarity_scores(input)['compound']
            return f"Polarity score: {score}"


    demo_text = "$MSFT No reason to not pick up this bargain for a bullish reversal"
    return(render_template('ai.html', demo_text=demo_text))

flask_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<!-- 'About Us' page content -->
<div class="container-fluid" id="homepage-content" style="margin-top: -5em;">
  <div class="row align-items-center">
     <div class="offset-lg-2 col-lg-8">
	   <h2 class="highlight">Our Story</h2>
	   <blockquote class="quote blockquote text-center">
	     <p class="mb=0">Facts only account for 10% of the reactions on the stock market; 
		 everything else is psychology.</p>
		 <footer class="blockquote-footer">Andr&eacute; Kostolany, Stock Market Investor
	  </blockquote>
	 </div>
    <div class="offset-lg-4 col-lg-4">
	  <img src="https://s.wsj.net/public/resources/images/OG-AE141_Social_J_20150420173657.jpg" 
	  class="center img-fluid" alt="Stock image of Twitter sentiment analysis">
	</div>

	<!-- Start of text -->
	<div class="offset-lg-2 col-lg-8 mt-2">
	  <p>Ever wished that you were part of the 1000% rally of GameStop's stocks? Or the 800% rally 
	  of Signal Advance's? Due to a Reddit coordinated short squeeze, and a two word tweet by Elon 
	  Musk respectively, prices of both stocks skyrocketed in a short period of time.</p>
	  <p>As with many other industries, the financial industry continues to shape - and to some extent,
	  is shaped by - information shared on the Internet, especially via social media. And while the 
	  aforementioned investments can be of high risk, these incidents clearly show the impact social media 
	  can have on stock prices. We aim to collect such information, mainly in the form of text, from social 
	  media to find a correlation between this information and change in stock prices and predict short term
	  price movements.</p>
	  <p>With the rise of young retail investors who increasingly exchange information on social media, we 
	  believe that such analysis will become very valuable to understand the market.</p>
	  <p>To The Moon aims to use natural language processing to process large amounts of social media 
	  posts on different stocks. By analysing these conversations over the internet, we provide users 
	  with the general sentiment surrounding the stocks that they wish to invest in.</p>
	  <h3 class="highlight">How it works</h3>
	  <img src="{{ url_for('static', filename='images/data_collection.png') }}" class="center img-fluid" alt="Overview of data collection process">
	  <p>The process begins with data collection. In order to train a machine learning model, we will 
	  require a large amount of relevant data. In this case, we need financial tweets and prices data 
	  about various stocks traded. We thus chose a set of 300 most actively traded stocks and used APIs 
	  from Twitter and Alpha Vantage to get the relevant data. We developed a script that can be run 
	  regularly to get these data and save them, and allowed us to collect sufficient data for training 
	  of machine learning models.<p>
	  <p>We then developed two machine learning models based on the data to predict whether a given
	  stock will rise or fall using the number of bullish tweets. Currently, both models have an accuracy 
	  of 61%, but this will be improved upon in further iterations as more data is collected.</p>
	  <h4>Overview</h4>
	  <img src="{{ url_for('static', filename='images/project_overview.png') }}" class="center img-fluid" alt="Mechanism overview">
	</div>
  </div>
</div>
{% endblock %}

flask_app/templates/ai.html
{% extends 'base.html' %}

{% block content %}
<!-- 'AI' page content -->
<div class="container-fluid" id="homepage-content" style="margin-top: -5em;">
  <div class="row align-items-center">
      <div class="offset-lg-2 col-lg-8">
        <h2 class="highlight">Our AI</h2>
      </div>

  <!-- Start of text -->
    <div class="offset-lg-2 col-lg-8 mt-2">
      <p>Artificial intelligence forms the core of our web application. In particular,
        we have trained two machine learning models to use in our application. We make use of
        <a href="https://scikit-learn.org/stable/", target="_blank">scikit-learn</a> for this purpose.
      </p>
      <p>
        The first model is a <strong>Random Forest Classifier</strong> which predicts whether the stock of a price
        will rise. This model is in charge of the main results shown whenever you search for the analysis of a stock. In this
        case, the confidence level is a measure of the probability which the model thinks its prediction is correct,
        based on data points it has previously seen.
      </p>
      <p>
        The second model is a <strong>LinearSVC</strong> model which classifies tweets into those that have a positive financial
        sentiment, and those with negative financial sentiments. While there are many pre-trained sentiment analysis models out there,
        not many of them are fine-tuned for financial texts. Try comparing the sentiment classifier meant for normal text below (using 
        <a href="https://github.com/cjhutto/vaderSentiment">vaderSentiment's</a> classifier), and the sentiment classifier that we have 
        trained. You can see that our classifier is more suited for financial text, or tweets in our case.
        <div id="text-classifier-demo">
          <form id="general-sentiment">
            <div>
              <label for="vader-input" class="form-label highlight">General sentiment classifier</label>
              <input type="text" class="form-control" id="vader-input" value="{{ demo_text }}">
              <div class="form-text">Polarity score is a value between -1 and 1, where 1 represents the most positive sentiment</div>
            </div>
            <p class="demo-result"></p>
          </form>

          <form method="POST" class="mt-3" id="financial-sentiment">
            <div>
              <label for="linearsvc-input" class="form-label highlight">Financial sentiment classifier</label>
              <input type="text" class="form-control" id="linearsvc-input" value="{{ demo_text }}">
              <div class="form-text">The confidence score represenst the distance from the decision hyperplane in the LinearSVC
                model, where a higher value means the model is more confident of its prediction
              </div>
            </div>
            <p class="demo-result"></p>
          </form>
        </div>
      </p>
      <p class="mt-5">
        For those interested in the technical details of our models, such as our data visualisation and training stages,
        check out these Jupyter notebooks!
        <ol>
          <li>
            <a href="https://www.kaggle.com/lyejiayang/1-twitter-data-exploration" target="_blank">Exploratory Data Analysis</a>
          </li>
          <li>
            <a href="https://www.kaggle.com/lyejiayang/2-tweets-classification" target="_blank">Tweets classification</a>
          </li>
          <li>
            <a href="https://www.kaggle.com/lyejiayang/3-stock-price-prediction-with-tweets-sentiment" target="_blank">Stock price prediction</a>
          </li>
          <li>
            <a href="https://www.kaggle.com/lyejiayang/4-stock-price-prediction-with-finbert-sentiment" target="_blank">Price prediction with finBert sentiment</a>
          </li>
        </ol>
      </p>
    </div>
  </div>
</div>
{% endblock %}

flask_app/templates/analysis.html
{% extends 'base.html' %}

{% block content %}
  <!-- Label for stock currently showing results for -->
  <div class="ticker-label">Showing results for: {{ company_name }} ({{ symbol }}) 
      <form id='add-favourites' action="/add-favourites" method="POST">
        <button type="submit" name="symbol" value={{ symbol }}>
          {% if is_favourite %}
            <!-- Solid star icon for favourited stock -->
            <i class="fas fa-star"></i>
          {% else %}
            <!-- Hollow star icon for non-favourited stock -->
            <i class="far fa-star"></i>
          {% endif %}
        </button>
      </form>
  </div> 

  <!-- Two square cards for emphasis of main results -->
  <div class="container-fluid row text-center">
    <div class="col-lg-6 d-flex justify-content-center">
      <div class="card result-display">
        <div class="card-body result-text">
          This stock will<span class="highlight"> {{ prediction }} </span>in the short term
        </div>
      </div>
    </div>
    <div class="col-lg-6 d-flex justify-content-center">
      <div class="card result-display">
        <div class="card-body result-text">
          Confidence level:<span class="highlight"> {{ confidence_level }}% </span>
        </div>
      </div>
    </div>
  </div>

  <!-- Section for analysis of social media posts -->
  <div class="container-fluid row">
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top bullish tweets</h2>
      <ul>
        {% for tweet in bullish_tweets %}
          <li class="py-2">
            {{ tweet.get('text') }} <a href={{ tweet.get("link") }} target="_blank">[Full tweet]</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top bearish tweets</h2>
      <ul>
        {% for tweet in bearish_tweets %}
          <li class="py-2">
            {{ tweet.get('text') }} <a href={{ tweet.get("link") }} target="_blank">[Full tweet]</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top news</h2>
      <ul>
        {% for article in news %}
          <li class="py-2">
            {{ article.get('title') }} <a href={{ article.get("link") }} target="_blank">[Link]</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <!-- Section for showing of price movements of given stock -->
  <!-- <br>
  <div class="flex-container">
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_year.png'" class="col-lg-1 flex-item">Year</button>
	  </div>
	  <div class="flex-item"> | </div>
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_month.png'" class="col-lg-1 flex-item">Month</button>
	  </div>
	  <div class="flex-item"> | </div>
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_week.png'" class="col-lg-1 flex-item show">Week</button>
	  </div>
  </div>
  
  <br>
  <div class="flex-container">
    <img id="graph" src="static/images/msft_week.png" class="img-fluid" alt="Graph of MSFT stock">
  </div>
  <br> -->
{% endblock %}

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To The Moon</title>

  <!-- Faivcon fetches -->
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
  <link rel="icon" href="/favicon.ico">
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  <!-- Google Fonts: Montserrat family -->
  <link rel="preconnect" href="https://fonts.gstatic.com"> 
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;500;600&display=swap" rel="stylesheet">
  <!-- Font awesome -->
  <script src="https://kit.fontawesome.com/b3685a7cf2.js" crossorigin="anonymous"></script>
</head>
<body class="dark sticky-top">
  <!-- Navigation bar -->
  <header>
    <nav class="navbar navbar-expand-lg px-2 py-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index.home') }}">
          <img src="{{ url_for('static', filename='images/logo.png') }}">
        </a>
        <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item px-4">
              <a class="nav-link header-link" aria-current="page" href="{{ url_for('index.home') }}">Home</a>
            </li>
            <li class="nav-item px-4">
              <a class="nav-link header-link" href="{{ url_for('index.about') }}">About</a>
            </li>
            <li class="nav-item px-4">
              <a class="nav-link header-link" href="{{ url_for('index.ai') }}">Our AI</a>
            </li>
            <li class="nav-item px-4">
              <a class="nav-link header-link" href="{{ url_for('index.contact') }}">Contact Us</a>
            </li>
            <li class="nav-item dropdown px-4">
              <a class="nav-link header-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Favourites
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if session.get('favourites', []) == [] %}
                    <li><a class="dropdown-item favourite-stocks disabled">No Stocks Added</a></li>
                {% else %}
                  {% for stock in session['favourites'] %}
                    <li><a class="dropdown-item favourite-stocks" href="{{ url_for('analysis.analysis', symbol=stock) }}">{{ stock }}</a></li>
                  {% endfor %}
                {% endif %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <!-- Loading text for general use -->
  <p class="centered hide" id="loading-text">Loading...</p>

  <!-- Main content section -->
  <section id="main-content">
    {% block content %}{% endblock %}
  </section>

  <!-- Bootstrap JS Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  <!-- jQuery and custom Javascript -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</body>
</html>

flask_app/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<!-- 'Contact Us' page content -->
<div class="container-fluid" id="homepage-content">
  <div class="row align-items-center">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8 justify-content-center">
      <p><center>If you like this content and/or have any feedback, reach out to us on twitter or 
	  drop us an email at orbitaltothemoon@gmail.com!</center></p>
    </div>
  </div>
</div>
{% endblock %}

flask_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div id="shooting-star-container">
  <div class="night">
    <div class="shooting-star"></div>
    <div class="shooting-star"></div>
    <div class="shooting-star"></div>
    <div class="shooting-star"></div>
    <div id="last-star" class="shooting-star"></div>
  </div>
</div>
<!-- Main homepage content -->
<div class="container-fluid" id="homepage-content">
  <div class="row align-items-center">
    <!-- Team name and hook -->
    <div class="col-lg-4">
      <h2 class="highlight" id="homepage-title">To The Moon</h2>
      <p id="homepage-hook">Using<span class="highlight"> artificial intelligence </span>
        to listen in on, and analyse conversations all over the internet</p>
    </div>
    <!-- Search bar to input stock ticker to analyse results for -->
    <div class="col-lg-8 justify-content-center">
      <div class="row">
        <div class="col-12 d-flex justify-content-center">
          <form id="search-form" method="POST">
            <div class="form-group search">
              <div class="input-group">
                <input autocomplete="off" type="text" name="ticker" class="form-control" placeholder="Stock ticker" aria-label="Stock ticker">
                <button id="analyse-button" class="btn btn-outline-secondary" type="submit">Analyse</button>
                <button id="loading-button" class="btn btn-outline-secondary hide" disabled>
                  <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...
                </button>
              </div>
            </div>
            <p class="recommended-text form-text mt-3">Check out these <a href="" data-bs-toggle="modal" data-bs-target="#recommendedStocks">recommended</a> stocks!</p>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-12 d-flex justify-content-center">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-dismissable" role="alert">
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Recommended stocks modal -->
<div class="modal fade" id="recommendedStocks" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Bullish stocks</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          Below is a list of stocks that were given a bullish prediction by our model, searched by other
          users within the past 24 hours.
        </p>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Stock symbol</th>
              <th scope="col">Confidence level</th>
              <th scope="col">Timestamp (GMT+8)</th>
            </tr>
          </thead>
          <tbody>
            {% if recommended_stocks == [] %}
              <tr>
                <td class="grey-text" colspan="3">There seems to be no bullish stocks searched by our users so far :(</td>
              </tr>
            {% else %}
              {% for stock in recommended_stocks %}
                <tr>
                  <td><a class="favourite-stocks" href="{{ url_for('analysis.analysis', symbol=stock.symbol) }}">{{ stock.symbol }}</a></td>
                  <td>{{ stock.confidence_level }}%</td>
                  <td>{{ stock.datetime }}</td>
                </tr>
              {% endfor %}
            {% endif %}
          </tbody>
        </table>
        <div class="pt-5"><small>Note: If the prediction was fetched some time ago, the sentiment may change based on more recent tweets.
          Check the most recent analysis by clicking on the link to the stocks!
        </small></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flask_app/templates/results.html
{% extends 'base.html' %}

{% block content %}
  <p class="ticker-label">Showing results for: Microsoft Corporation (NYSE:MSFT)</p>
  <div class="container-fluid row text-center">
    <div class="col-lg-6 d-flex justify-content-center">
      <div class="card result-display">
        <div class="card-body result-text">
          This stock will<span class="highlight"> RISE </span>in the short term
        </div>
      </div>
    </div>
    <div class="col-lg-6 d-flex justify-content-center">
      <div class="card result-display">
        <div class="card-body result-text">
          Confidence level:<span class="highlight"> 92.34% </span>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid row">
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top tweets</h2>
      <ul>
        <li>Microsoft Corporation announces acquisition of...<a href=""> [Full Post]</a></li>
        <li>Microsoft to report earnings on...<a href=""> [Full Post]</a></li>
      </ul>
    </div>
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top reddit posts</h2>
      <ul>
        <li>Microsoft to attend technology conference at...<a href=""> [Full Post]</a></li>
      </ul>
    </div>
    <div class="col-lg-4 media-posts">
      <h2 class="highlight">Top news</h2>
      <ul>
        <li>A company at a great price: Microsoft Corporation<a href=""> [Full Post]</a></li>
      </ul>
    </div>
  </div>

  <br>
  <div class="flex-container">
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_year.png'" class="col-lg-1 flex-item">Year</button>
	  </div>
	  <div class="flex-item"> | </div>
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_month.png'" class="col-lg-1 flex-item">Month</button>
	  </div>
	  <div class="flex-item"> | </div>
	  <div>
	    <button onclick="document.getElementById('graph').src='static/images/msft_week.png'" class="col-lg-1 flex-item show">Week</button>
	  </div>
  </div>
  
  <br>
  <div class="flex-container">
    <img id="graph" src="static/images/msft_week.png" class="img-fluid" alt="Graph of MSFT stock">
  </div>
  <br>
{% endblock %}